arb-dir: assets/l10n
output-dir: lib/src/localization
template-arb-file: intl_en.arb
output-localization-file: ui_kit_localizations.dart
output-class: UiKitLocalizations
preferred-supported-locales: [en, ru]
