targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          include:
            - lib/src/presentation/pages/**.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          include:
            - lib/src/presentation/router/**.dart
      freezed:freezed:
        generate_for:
          include:
            - lib/src/presentation/states/**/**.dart
            - lib/src/domain/models/**.dart
            - lib/src/data/data_sources/**.dart
