arb-dir: assets/l10n
output-dir: lib/src/presentation/localization
template-arb-file: intl_en.arb
output-localization-file: auth_localizations.dart
output-class: AuthLocalizations
preferred-supported-locales: [en, ru]
